"""Export the Station Mixer bench as a native web component for revaudio.net: public/station-mixer/.

Why not an iframe: the live site sends X-Frame-Options: DENY and a frame-src without 'self', so even a same-origin
iframe is blocked (it only worked on the dev server). The live CSP also has font-src 'self' (no Google Fonts).

Output (all served from revaudio.net itself):
  station-mixer.js   <station-mixer> custom element: shadow DOM (the bench CSS can't touch the site and the site's
                     CSS can't touch it), built only when it scrolls near the viewport (images load late), audio only
                     on PLAY. Generated from bench/station-mixer-bench.html, so the bench stays the single source.
  fonts.css + fonts/ Permanent Marker, Gochi Hand, Yellowtail, Cinzel 700 (latin woff2). Inter / Oswald / VT323 come
                     from the site's own fonts.css.
  audio/*.m4a        AAC 160k, each file = the loop + half a bar of padding both sides (taken from the loop itself),
                     the player loops the window inside, so encoder priming can never click at the loop point.
  img/               the bench images the page uses.
Usage: python tools/station-mixer/export_component.py"""
import json, os, re, shutil, subprocess, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BENCH = os.path.join(ROOT, 'bench')
SRC = os.path.join(BENCH, 'assets', 'station-mixer')
OUT = os.path.join(ROOT, 'public', 'station-mixer')
SR, L, PAD = 48000, 1024000, 64000            # PAD = half a bar at 90 BPM
URL = '/station-mixer/'

html = open(os.path.join(BENCH, 'station-mixer-bench.html'), encoding='utf-8').read().replace('\r\n', '\n')
css = re.search(r'<style>(.*?)</style>', html, re.S).group(1)
body = re.search(r'<body>(.*?)<script>', html, re.S).group(1)
script = re.search(r'<script>\s*(.*?)</script>\s*</body>', html, re.S).group(1)

def sub(s, a, b, count=None):
    assert a in s, a[:80]
    return s.replace(a, b) if count is None else s.replace(a, b, count)

# ---- CSS: page selectors -> :host ----
css = sub(css, ':root{', ':host{', 1)
css = sub(css, "html,body{background:var(--page);color:var(--ink);font-family:Inter,'Segoe UI',Arial,sans-serif}",
          ":host{display:block;color:var(--ink);font-family:Inter,'Segoe UI',Arial,sans-serif}")
css = sub(css, 'body{min-height:100vh;padding:28px 16px 60px}', '')
css = re.sub(r'body(\.[\w-]+|:not\(\.[\w-]+\))', lambda m: f':host({m.group(1)})', css)
assert not re.search(r'(^|[}\s,])body[\s.:{,]', re.sub(r'/\*.*?\*/', '', css, flags=re.S)), 'a body selector survived'
css = css.replace('assets/station-mixer/img/', URL + 'img/')

# ---- markup ----
body = re.sub(r'<div class="benchhead">.*?</div>', '', body, count=1, flags=re.S)
body = sub(body, '<p class="note" id="note"></p>', '')
body = body.replace('assets/station-mixer/img/', URL + 'img/')

# ---- script: document -> shadow root, audio -> padded m4a ----
s = script
s = sub(s, "const $ = s => document.querySelector(s);", "const $ = s => root.querySelector(s);")
s = s.replace('document.querySelectorAll(', 'root.querySelectorAll(').replace('document.querySelector(', 'root.querySelector(')
s = s.replace('document.body.classList', 'host.classList')
s = s.replace('document.addEventListener(', 'root.addEventListener(')
s = s.replace('assets/station-mixer/img/', URL + 'img/')
s = sub(s, "const AUD = 'assets/station-mixer/audio/', EXT = '.flac', PADS = 0;",
        f"const AUD = '{URL}audio/', EXT = '.m4a', PADS = {PAD}/{SR};")   # loop window inside the padded AAC file
s = sub(s, "onerror=\"this.parentNode.classList.add('noimg');buildEmblems()\"", "onerror=\"this.parentNode.classList.add('noimg')\"")
# fonts load lazily inside the component: wait for the ones the notes / emblems / glass measure with
s = sub(s, "(document.fonts ? document.fonts.ready : Promise.resolve())",
        "(document.fonts ? Promise.all(['17px \"Gochi Hand\"','19px \"Permanent Marker\"','22px Yellowtail','700 17px Cinzel','46px VT323','600 13px Oswald'].map(f => document.fonts.load(f).catch(() => null))).then(() => document.fonts.ready) : Promise.resolve())")
# the bench-only levels note + the dev calibration helper
s = re.sub(r"fetch\(AUD\+'manifest\.json'\).*?\.catch\(\(\)=>\{\}\);\n", '', s, flags=re.S)
s = re.sub(r"/\* ---------- calibration \(dev\).*?\n};\n", '', s, flags=re.S)
assert 'window.calibrateRL' not in s and "AUD+'manifest.json'" not in s
assert 'document.query' not in s and 'document.body' not in s

js = f"""/* Radio Roulette Station Mixer: <station-mixer> web component.
   GENERATED by tools/station-mixer/export_component.py from bench/station-mixer-bench.html. Edit the bench, re-export. */
(() => {{
const CSS = {json.dumps(css)};
const HTML = {json.dumps(body)};
class StationMixer extends HTMLElement {{
  connectedCallback() {{
    if (this._armed) return; this._armed = true;
    // build only when it comes near the viewport: its ~4 MB of images never slow the page's first paint
    const io = new IntersectionObserver(es => {{ if (es.some(e => e.isIntersecting)) {{ io.disconnect(); this.build(); }} }}, {{ rootMargin: '800px 0px' }});
    io.observe(this);
  }}
  build() {{
    const host = this, root = this.attachShadow({{ mode: 'open' }});
    root.innerHTML = `<style>${{CSS}}</style>` + HTML;
    host.classList.add('ready');
{s}
  }}
}}
customElements.define('station-mixer', StationMixer);
}})();
"""

# ---- write ----
for d in ('audio', 'img', 'fonts'):
    os.makedirs(os.path.join(OUT, d), exist_ok=True)
for dp, _, fns in os.walk(OUT):               # generated folder: clear our own files (Windows desktop.ini stays)
    for fn in fns:
        if fn.lower() != 'desktop.ini':
            os.remove(os.path.join(dp, fn))
open(os.path.join(OUT, 'station-mixer.js'), 'w', encoding='utf-8').write(js)

# images actually referenced
used = {f for f in re.findall(r'/station-mixer/img/([\w.-]+)', css + body + s) if '.' in f}
used |= {f'emblem-{w}.png' for w in ('drums', 'bass', 'keys', 'guitar', 'master')}   # built at runtime: emblem-${name}.png
for f in used:
    shutil.copy2(os.path.join(SRC, 'img', f), os.path.join(OUT, 'img', f))

# fonts: latin woff2 from Google Fonts, served from the site
fams = {'Permanent Marker': 'Permanent+Marker', 'Gochi Hand': 'Gochi+Hand', 'Yellowtail': 'Yellowtail', 'Cinzel': 'Cinzel:wght@700'}
ua = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36'}
faces = []
for fam, q in fams.items():
    cssg = urllib.request.urlopen(urllib.request.Request(f'https://fonts.googleapis.com/css2?family={q}&display=swap', headers=ua)).read().decode()
    blocks = re.findall(r'/\* (\S+) \*/\s*@font-face \{(.*?)\}', cssg, re.S)
    for subset, blk in blocks:
        if subset != 'latin':
            continue
        url = re.search(r'url\((https://[^)]+\.woff2)\)', blk).group(1)
        name = fam.lower().replace(' ', '-') + '-latin.woff2'
        open(os.path.join(OUT, 'fonts', name), 'wb').write(urllib.request.urlopen(urllib.request.Request(url, headers=ua)).read())
        weight = re.search(r'font-weight: (\d+)', blk).group(1)
        urange = re.search(r'unicode-range: ([^;]+);', blk).group(1)
        faces.append(f"@font-face{{font-family:'{fam}';font-style:normal;font-weight:{weight};font-display:swap;"
                     f"src:url('{URL}fonts/{name}') format('woff2');unicode-range:{urange}}}")
open(os.path.join(OUT, 'fonts.css'), 'w', encoding='utf-8').write(
    '/* Station Mixer fonts (latin, self-hosted: the live CSP is font-src self). Generated by export_component.py */\n' + '\n'.join(faces) + '\n')

# audio: loop + half a bar each side, AAC 160k
def load(path):
    raw = subprocess.run(['ffmpeg', '-v', 'error', '-i', path, '-f', 'f32le', '-ac', '2', '-ar', str(SR), '-'], capture_output=True, check=True).stdout
    return raw
import numpy as np
n = 0
for f in sorted(os.listdir(os.path.join(SRC, 'audio'))):
    if not f.endswith('.flac') or f.startswith('rl_'):
        continue
    x = np.frombuffer(load(os.path.join(SRC, 'audio', f)), dtype=np.float32).reshape(-1, 2)
    assert len(x) == L, (f, len(x))
    padded = np.concatenate([x[-PAD:], x, x[:PAD]])
    subprocess.run(['ffmpeg', '-v', 'error', '-y', '-f', 'f32le', '-ar', str(SR), '-ac', '2', '-i', '-',
                    '-c:a', 'aac', '-b:a', '160k', '-movflags', '+faststart', os.path.join(OUT, 'audio', f[:-5] + '.m4a')],
                   input=padded.astype(np.float32).tobytes(), check=True)
    n += 1

size = sum(os.path.getsize(os.path.join(dp, fn)) for dp, _, fns in os.walk(OUT) for fn in fns)
print(f'exported {OUT}: {n} m4a, {len(used)} images, {len(faces)} font faces, {size/1e6:.1f} MB total')
