import { CIRCUIT_LAPS } from './circuits.data';

/**
 * The 8 iconic circuits on #drive (Dan 2026-10-02: real shapes, country names
 * only). The data is the plugin's own (circuits.data.ts, generated by
 * tools/gen-drift-circuits.mjs from Drift's f1-tracks-data.js); this file turns
 * a lap into the pan the same way TrackEngine.h does: the car's corner
 * curvature x width, a Scandinavian flick against the corner 0.35 s ahead, then
 * the shared PanSpring (tracks.ts). Right-hand corner = pan right.
 */
export interface Lap { s: Float32Array; c: Float32Array }

const laps = new Map<number, Lap>();
for (const l of CIRCUIT_LAPS) {
  const n = l.ds.length, s = new Float32Array(n), c = new Float32Array(n);
  let acc = 0;
  for (let k = 0; k < n; k++) { acc += l.ds[k]; s[k] = acc / 1e4; c[k] = l.c[k] / 100; }
  laps.set(l.id, { s, c });
}
export const lapOf = (id: number) => laps.get(id) ?? laps.values().next().value!;

const FLICK = 0.7;   // kFlick: counter-steer amount at INTENSITY 1

/** Car radius in a circuit's viewBox units: the 7 px it had on the 295 x 228 glass. */
export const carR = (vb: string) => { const [, , w, h] = vb.split(/\s+/).map(Number); return (7 * Math.max(w / 295, h / 228)).toFixed(4); };

/** FREE lap time of a circuit (TrackEngine.h: 45 s .. 3 s log), 12 s at the default LAP. */
export const circuitPeriod = (lap01: number) => 3 * Math.pow(45 / 3, 1 - lap01);

const at = (arr: Float32Array, ph: number) => {
  const n = arr.length, u = (ph - Math.floor(ph)) * n, i = Math.floor(u) % n, f = u - Math.floor(u);
  return arr[i] * (1 - f) + arr[(i + 1) % n] * f;
};

/** Where the car is along the outline, 0..1 of its length (the lap wraps 1 -> 0). */
export function lapPos(lap: Lap, ph: number): number {
  const n = lap.s.length, u = (ph - Math.floor(ph)) * n, i = Math.floor(u) % n, f = u - Math.floor(u);
  const a = lap.s[i], b = i + 1 < n ? lap.s[i + 1] : 1;
  return (a + (b - a) * f) % 1;
}

/** The pan the car is steering toward (before the spring), -1..1. */
export function lapTarget(lap: Lap, ph: number, width: number, intensity: number, periodSec: number): number {
  const raw = at(lap.c, ph) * width;
  const ahead = at(lap.c, ph + Math.min(0.08, 0.35 / periodSec)) * width;
  return raw - FLICK * intensity * (ahead - raw);
}

/** Park on the start line when it sits on a straight, else on the first straight after it. */
export function restPhase(lap: Lap): number {
  const n = lap.c.length;
  let best = 0;
  for (let k = 0; k < n; k++) {
    if (Math.abs(lap.c[k]) < 0.02) return k / n;
    if (Math.abs(lap.c[k]) < Math.abs(lap.c[best])) best = k;
  }
  return best / n;
}
