import { CIRCUIT_LAPS } from './circuits.data';

/**
 * The 8 iconic circuits on #drive (Dan 2026-10-02: real shapes, country names
 * only). The data is the plugin's own (circuits.data.ts, generated by
 * tools/gen-drift-circuits.mjs from Drift's f1-tracks-data.js); this file runs a
 * lap the way TrackEngine.h does, at any INTENSITY (the #drive fader, live):
 * the car's place on the lap = lerp(calm, rally) time warp by INTENSITY (it
 * brakes harder into corners as INTENSITY rises), the pan = corner curvature
 * x width, a Scandinavian flick against the corner 0.35 s ahead, then the
 * shared PanSpring (tracks.ts). Right-hand corner = pan right.
 */
export interface Lap { c: Float32Array; a: Float32Array; fc: Float32Array; fr: Float32Array }

const undelta = (d: number[], k: number) => {
  const out = new Float32Array(d.length);
  let acc = 0;
  for (let i = 0; i < d.length; i++) { acc += d[i]; out[i] = acc / k; }
  return out;
};
const laps = new Map<number, Lap>();
for (const l of CIRCUIT_LAPS) laps.set(l.id, { c: undelta(l.c, 100), a: undelta(l.a, 1e4), fc: undelta(l.fc, 4), fr: undelta(l.fr, 4) });
export const lapOf = (id: number) => laps.get(id) ?? laps.values().next().value!;

const FLICK = 0.7;   // kFlick: counter-steer amount at INTENSITY 1

/** Car radius in a circuit's viewBox units: the 7 px it had on the 295 x 228 glass. */
export const carR = (vb: string) => { const [, , w, h] = vb.split(/\s+/).map(Number); return (7 * Math.max(w / 295, h / 228)).toFixed(4); };

/** FREE lap time of a circuit (TrackEngine.h: 45 s .. 3 s log), 12 s at the default LAP. */
export const circuitPeriod = (lap01: number) => 3 * Math.pow(45 / 3, 1 - lap01);

const wrap = (x: number) => x - Math.floor(x);
/** Linear read of a time table at lap phase ph (0..1, wraps); the index climbs 0..span over a lap. */
const atTime = (arr: Float32Array, ph: number, span: number) => {
  const n = arr.length, u = wrap(ph) * n, i = Math.floor(u) % n, f = u - Math.floor(u);
  return arr[i] + ((i + 1 < n ? arr[i + 1] : arr[0] + span) - arr[i]) * f;
};
/** Linear read of a per-point table at fractional point index fi (wraps). */
const atPoint = (arr: Float32Array, fi: number, span = 0) => {
  const n = arr.length, x = ((fi % n) + n) % n, i = Math.floor(x), f = x - i;
  return arr[i] + ((i + 1 < n ? arr[i + 1] : arr[0] + span) - arr[i]) * f;
};
/** The point index the car is at: the calm and rally time warps morphed by INTENSITY. */
const idx = (lap: Lap, ph: number, intensity: number) => {
  const g = lap.c.length, c = atTime(lap.fc, ph, g);
  return c + (atTime(lap.fr, ph, g) - c) * intensity;
};

/** Where the car is along the outline, 0..1 of its length. */
export const lapPos = (lap: Lap, ph: number, intensity: number) => wrap(atPoint(lap.a, idx(lap, ph, intensity), 1));

/** The pan the car is steering toward (before the spring), -1..1. */
export function lapTarget(lap: Lap, ph: number, width: number, intensity: number, periodSec: number): number {
  const raw = atPoint(lap.c, idx(lap, ph, intensity)) * width;
  const ahead = atPoint(lap.c, idx(lap, ph + Math.min(0.08, 0.35 / periodSec), intensity)) * width;
  return raw - FLICK * intensity * (ahead - raw);
}

/** Park on the start line when it sits on a straight, else on the first straight after it. */
export function restPhase(lap: Lap, intensity: number): number {
  const n = lap.fc.length;
  let best = 0, bv = Infinity;
  for (let k = 0; k < n; k++) {
    const v = Math.abs(atPoint(lap.c, idx(lap, k / n, intensity)));
    if (v < 0.02) return k / n;
    if (v < bv) { bv = v; best = k; }
  }
  return best / n;
}
